"""Merge eval_matrix.py + eval_matrix_xenv.py per-method JSONs (across ONE OR MORE dirs) into
(1) a console table and (2) LaTeX rows for exp_plan tab:main (bit-acc per attack) +
tab:main-quality (PSNR/SSIM/mean-TPR). Attacks are unioned per method across all dirs.
Usage: python make_matrix_table.py <dir> [<dir2> ...] [--tex out.tex]
"""
import json, glob, os, sys, argparse
import numpy as np

# display order (signal | geometry | vae | regen | advanced | cross-env) + short names
COL = [("clean","Clean"),("bright","Brgt"),("contrast","Cont"),("jpeg","JPEG"),("blur","Blur"),
       ("noise","Noise"),("bm3d","BM3D"),("crop75","Crp75"),("crop50","Crp50"),("rot9","Rot9"),
       ("rs256","RS256"),("hflip","HFlip"),("crop_jpeg","CrpJ"),("vae_b","VAE-B"),("vae_c","VAE-C"),
       ("regen","Regen"),("rinse2x","Rin2"),("rinse4x","Rin4"),
       ("editing","Edit"),("img2video","I2V"),("ctrlregen","CtrlR"),("unmarker","UnMk")]
ROW_ORDER = ["DwtDct","DwtDctSvd","RivaGAN","TrustMark-B","VINE-B","VINE-R","Ours","Ours-B+geo","Ours+geo"]

def load(dirs):
    out = {}
    for d in dirs:
        for f in sorted(glob.glob(os.path.join(d, "*.json"))):
            j = json.load(open(f)); m = j.get("method")
            if not m: continue
            o = out.setdefault(m, {"method": m, "n_bits": j.get("n_bits"), "psnr": None, "ssim": None, "attacks": {}})
            if j.get("n_bits") is not None: o["n_bits"] = j["n_bits"]
            if j.get("psnr") is not None: o["psnr"] = j["psnr"]
            if j.get("ssim") is not None: o["ssim"] = j["ssim"]
            o["attacks"].update(j.get("attacks", {}))
    return out

def cols_present(data):
    return [c for c in COL if any(c[0] in j["attacks"] for j in data.values())]

def ba(j, c):
    v = j["attacks"].get(c, {}).get("bit_acc"); return v
def tpr(j, c):
    v = j["attacks"].get(c, {}).get("tpr"); return v
def avg(j, cols):
    """Mean over ATTACKED columns only -- including `clean` would inflate every row."""
    vs = [ba(j, c) for c, _ in cols if c != "clean" and ba(j, c) is not None]
    return float(np.mean(vs)) if vs else None
def f2(x, w=6): return f"{x:>{w}.2f}" if x is not None else f"{'-':>{w}s}"

def console(data):
    cols = cols_present(data)
    print("=== BIT-ACCURACY (per attack) ===")
    print(f"{'method':12s}{'bits':>5s}{'PSNR':>6s}{'SSIM':>6s} " + " ".join(f"{n:>6s}" for _, n in cols) + f"{'AVG':>7s}{'COV':>5s}")
    for m in ROW_ORDER:
        j = data.get(m)
        if not j: continue
        cells = " ".join(f2(ba(j, c)) for c, _ in cols)
        ps = f"{j['psnr']:>6.1f}" if j['psnr'] is not None else f"{'-':>6s}"
        ss = f"{j['ssim']:>6.3f}" if j['ssim'] is not None else f"{'-':>6s}"
        av = avg(j, cols); avs = f"{av:>7.2f}" if av is not None else f"{'-':>7s}"
        cv = sum(1 for c, _ in cols if c != "clean" and (tpr(j, c) or 0) >= 0.95)
        print(f"{m:12s}{(j['n_bits'] or 0):>5d}{ps}{ss} {cells}{avs}{cv:>5d}")
    print("\n=== DETECTION TPR@1%FPR (per attack) ===")
    print(f"{'method':12s} " + " ".join(f"{n:>6s}" for _, n in cols))
    for m in ROW_ORDER:
        j = data.get(m)
        if not j: continue
        print(f"{m:12s} " + " ".join(f2(tpr(j, c)) for c, _ in cols))

def best_per_col(data, cols, get):
    """col -> the max value present in that column, for bolding."""
    out = {}
    for c, _ in cols:
        vs = [get(j, c) for j in data.values() if get(j, c) is not None]
        if vs: out[c] = max(vs)
    return out

def cell(v, best, tol=5e-3):
    if v is None: return "\\FILL"
    t = f"{v:.2f}"
    return f"\\textbf{{{t}}}" if best is not None and v >= best - tol else t

def latex(data, path):
    cols = cols_present(data); L = []
    bcol = best_per_col(data, cols, ba)
    avs_all = [avg(j, cols) for j in data.values() if avg(j, cols) is not None]
    bavg = max(avs_all) if avs_all else None
    L.append("% --- auto-generated by make_matrix_table.py (bit-acc per attack) ---")
    L.append("\\begin{tabular}{l r " + "c" * len(cols) + " c}\n\\toprule")
    L.append("Method & bits & " + " & ".join(n for _, n in cols) + " & Avg \\\\\n\\midrule")
    for m in ROW_ORDER:
        j = data.get(m)
        if not j: continue
        cells = " & ".join(cell(ba(j, c), bcol.get(c)) for c, _ in cols)
        av = avg(j, cols); avs = cell(av, bavg)
        pre = "\\rowcolor{hl}\n" if m == "Ours" else ""; nm = "\\textbf{Ours}" if m == "Ours" else m
        L.append(f"{pre}{nm} & {j['n_bits'] or ''} & {cells} & {avs} \\\\")
    L.append("\\bottomrule\n\\end{tabular}")
    L.append("\n% --- quality + mean detection ---")
    n_att = len([c for c, _ in cols if c != "clean"])
    def covered(j, thr=0.95):
        """Attacks this method actually survives at its own threshold. Fidelity is only comparable
        between methods that cover the same requirement, so coverage is reported beside PSNR."""
        return sum(1 for c, _ in cols if c != "clean"
                   and (tpr(j, c) is not None) and tpr(j, c) >= thr)
    L.append("\\begin{tabular}{l r c c c c}\n\\toprule\nMethod & bits & PSNR & SSIM & mean TPR@1\\%FPR & attacks covered \\\\\n\\midrule")
    def mtpr(j):
        v = [tpr(j, c) for c, _ in cols if c != "clean" and tpr(j, c) is not None]
        return float(np.mean(v)) if v else None
    bp = max([j["psnr"] for j in data.values() if j["psnr"] is not None] or [None])
    bs = max([j["ssim"] for j in data.values() if j["ssim"] is not None] or [None])
    bt = max([x for x in (mtpr(j) for j in data.values()) if x is not None] or [None])
    bcv = max(covered(j) for j in data.values())
    for m in ROW_ORDER:
        j = data.get(m)
        if not j: continue
        mv = mtpr(j)
        mt = ("\\textbf{%.2f}" % mv) if (mv is not None and bt is not None and mv >= bt - 5e-3) else (f"{mv:.2f}" if mv is not None else "\\FILL")
        ps = ("\\textbf{%.2f}" % j["psnr"]) if (j["psnr"] is not None and bp is not None and j["psnr"] >= bp - 5e-3) else (f"{j['psnr']:.2f}" if j["psnr"] is not None else "\\FILL")
        ss = ("\\textbf{%.3f}" % j["ssim"]) if (j["ssim"] is not None and bs is not None and j["ssim"] >= bs - 5e-4) else (f"{j['ssim']:.3f}" if j["ssim"] is not None else "\\FILL")
        pre = "\\rowcolor{hl}\n" if m == "Ours" else ""; nm = "\\textbf{Ours}" if m == "Ours" else m
        cv = covered(j); cvs = ("\\textbf{%d/%d}" % (cv, n_att)) if cv == bcv else f"{cv}/{n_att}"
        L.append(f"{pre}{nm} & {j['n_bits'] or ''} & {ps} & {ss} & {mt} & {cvs} \\\\")
    L.append("\\bottomrule\n\\end{tabular}")
    open(path, "w").write("\n".join(L)); print(f"\n[latex] -> {path}")

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("dirs", nargs="+"); ap.add_argument("--tex", default=None)
    a = ap.parse_args()
    data = load(a.dirs)
    if not data: sys.exit("no JSONs found")
    console(data)
    if a.tex: latex(data, a.tex)
