"""Half-widths of the 95% confidence interval on every rate in the main table.

Reads only the committed evaluation snapshot, so the table is reproducible from
the repository alone:

    python scripts/export_confidence_intervals.py --output tab

Scenario columns are Wilson intervals on the scenario rate. The Avg. column
propagates the five half-widths through the unweighted mean that defines the
main-table Avg. metric, treating the scenarios as independent. The Wilson form
is used rather than the normal approximation because several scenario rates sit
at 0 or 100 percent, where the normal interval collapses to zero width.
"""
import argparse
import json
import math
from pathlib import Path

PAPER = Path(__file__).resolve().parent.parent
SNAPSHOT = PAPER / 'data/main_no_ctrlregen07_20260924.json'
SCENARIOS = ['S1', 'S2', 'S3', 'S4', 'S5']
Z = 1.959963984540054
ROWS = [('StegaStamp', 'StegaStamp'), ('MaskWM', 'MaskWM'), ('VINE', 'VINE'),
        ('TrustMark', 'TrustMark'), ('VideoSeal', 'VideoSeal'),
        ('VINEGeo', 'VINE + Geo.'), ('TrustMarkGeo', 'TrustMark + Geo.'),
        ('Fixed1', 'Enumeration'), ('EnumGeo', 'Enumeration + Geo.'),
        ('Greedy06', r'\sysgreedy{}'), ('SMT06', r'\sysfull{}')]


def wilson_half_width(accepted, n):
    p = accepted / n
    return 100 * Z * math.sqrt(p * (1 - p) / n + Z * Z / (4 * n * n)) / (1 + Z * Z / n)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--output', type=Path, default=PAPER / 'tab')
    output = ap.parse_args().output
    summary = json.loads(SNAPSHOT.read_bytes())['summary']
    counts = {s: summary['SMT06']['scenarios'][s]['n'] for s in SCENARIOS}
    assert sum(counts.values()) == 7321
    lines = []
    for key, label in ROWS:
        scenes = summary[key]['scenarios']
        assert all(scenes[s]['n'] == counts[s] for s in SCENARIOS), key
        widths = [wilson_half_width(scenes[s]['accepted'], scenes[s]['n']) for s in SCENARIOS]
        average = math.sqrt(sum(w * w for w in widths)) / len(SCENARIOS)
        lines.append(f'{label} & ' + ' & '.join(f'{w:.2f}' for w in widths + [average]) + r' \\')
    sizes = ', '.join(f'${counts[s]:,}$'.replace(',', '{,}') for s in SCENARIOS)
    tex = (r'''% generated by scripts/export_confidence_intervals.py
\begin{table}[!t]
\centering
\caption{Half-width of the 95\% confidence interval on every request-satisfaction
rate in Table~\ref{tab:main}, in percentage points.}
\label{tab:confidence-intervals}
\papertablestyle
\resizebox{\linewidth}{!}{%
\begin{tabular}{@{}l cccccc@{}}
\toprule
\toprule
Method & S1 & S2 & S3 & S4 & S5 & \textbf{Avg.} \\
\midrule
''' + '\n'.join(lines) + r'''
\bottomrule
\bottomrule
\end{tabular}}
\papertablenote{Add and subtract the entry from the corresponding rate in
Table~\ref{tab:main}. Scenario columns are Wilson intervals at ''' + sizes +
r''' requests; the Avg. column propagates the five half-widths through the
unweighted mean as $\frac{1}{5}\sqrt{\sum_s h_s^2}$, treating the scenarios as
independent.}
\end{table}
''')
    (output / 'confidence_intervals.tex').write_text(tex)
    print(f'wrote {output / "confidence_intervals.tex"}')


if __name__ == '__main__':
    main()
